name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on:       
      group: cuda-gpu-runner-group
    
    steps:
    - uses: actions/checkout@v4
    - name: check_gpu
      run: 
        CODEBLOCK="\`\`\`"
        echo $CODEBLOCK > report.md
        nvidia-smi >> report.md
        echo $CODEBLOCK >> report.md

        cml-send-comment report.md
